export const BASE_URL = "https://120army.com/api/";
export const isloginCheckUserId = "";
export const autoCompleteUrl =
  "https://maps.googleapis.com/maps/api/place/autocomplete/json";
export const autocompleteDetails =
  "https://maps.googleapis.com/maps/api/place/details/json";
export const googleApiKey = "AIzaSyAwnPm0pAcIiMcMIeNFRxPmg-6OL_t3YFI";
export const placeDetails = "https://maps.googleapis.com/maps/api/geocode/json";
export const routes = {
  getRegistration: BASE_URL + "registration",
  getLogIn: BASE_URL + "login",
  getHomeList: BASE_URL + "homeList",
  getPrayerList: BASE_URL + "prayerListByEachOrganizer",
  getPrayerDetails: BASE_URL + "prayer_details",
  getUpcomingPrayer: BASE_URL + "ListofupcomingPrayers",
  getProfile: BASE_URL + "profile",
  getAllPrayer: BASE_URL + "ListofPrayers",
  ListofnewPrayers: BASE_URL + "ListofnewPrayers",
  ListofupcomingPrayer: BASE_URL + "ListofupcomingPrayer",
  userJoinedPrayer: BASE_URL + "userJoinedPrayer",
  featured_product_list: BASE_URL + "featured_product_list",
  product_list: BASE_URL + "product_list",
  product_category: BASE_URL + "product_category",
  productByCategory: BASE_URL + "productByCategory",
  add_to_cart: BASE_URL + "add_to_cart",
  total_cart: BASE_URL + "total_cart",
  cart_list: BASE_URL + "cart_list",
  forgotPassword: BASE_URL + "send_forget_password",
  setPassword: BASE_URL + "set_new_password",
  getPrivacyPolicy: BASE_URL + "privacy_policy",
  getTermsAndCondition: BASE_URL + "term_and_conditions",
  getDeleteAccount: BASE_URL + "delete_account",
  getAddprodcust: BASE_URL + "add_podcast",
  getpodcastdetaild: BASE_URL + "podcast_details",
  getListofPodcast: BASE_URL + "ListofPodcast",
  getLikedPodcast: BASE_URL + "likedPodcast",
  getUserlike: BASE_URL + "userlikedPodcast",
  getVideoDetails: BASE_URL + "video_details",
  getAllVideoList: BASE_URL + "allVideoList",
  getSocial_user_list: BASE_URL + "social_user_list",
  getsocialListByUser: BASE_URL + "socialListByUser",
  getuser_post_like: BASE_URL + "user_post_like",
  getget_post_comment: BASE_URL + "get_post_comment",
  getPostCommentReply: BASE_URL + "add_post_comment_rply",
  getCommentReply: BASE_URL + "get_comment_reply",
  getadd_post_comment: BASE_URL + "add_post_comment",
  getaddLikeForEachComment: BASE_URL + "addLikeForEachComment",
  getuser_post_details: BASE_URL + "user_post_details",
  getOrganizationList: BASE_URL + "getOrganizationList",
  viewAllOrganization: BASE_URL + "viewAllOrganization",
  getOrganizationDetails: BASE_URL + "organizationDetails",
  getjoined_organization: BASE_URL + "joined_organization",
  getProductBycategory: BASE_URL + "productByCategory",
  getUpdateCartQuantity: BASE_URL + "update_cart_list",
  getRemoveCart: BASE_URL + "remove_cart_list",
  getAddAddress: BASE_URL + "add_address",
  getUserAddressList: BASE_URL + "userAddress_list",
  getPlaceOrder: BASE_URL + "place_order",
  getProductdetails: BASE_URL + "productDetails",
  getDonationList: BASE_URL + "getOrganizationList",
  getdonation_details: BASE_URL + "donation_details",
  filter_search: BASE_URL + "filter_search",
  getpodcastListByEachOrganizer: BASE_URL + "podcastListByEachOrganizer",
  getVideoList: BASE_URL + "videoListByEachOrganizer",
  getDonationlistorganization: BASE_URL + "donation_list",
  getOrderList: BASE_URL + "order_list",
};
